# Site settings
title: Nathanael Smith
email: contact@nathanaelsmith.org
description: Nathanael Smith is a graduate student in philosophy at the University of Rochester who works primarily in epistemology and metaphysics, the digital humanities. Previously a student at Western Michigan University and the University of Oxford, he also likes to learn code and make websites and explore the digital humanities.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nathanaelsmith.org" # the base hostname & protocol for your site
twitter_username: Philoso_Smith
github_username:  ndsmith
facebook_username: nathanael.d.smith
orcid_id: 0000-0001-7326-0389

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - bourbon
